### ISSUE TITLE
Add support for comments in map files

### ISSUE THREAD

**Issue by Slimd0g** [TThemes/TThemeConverter#6]
I've got an override map with commented colors, not to forget meanings.

```
Converting desktop theme to android...
Warning: chat_inVenueInfoSelectedText is missing form your theme file
Warning: chat_messageLinkOut is missing form your theme file
Warning: chat_outVenueInfoSelectedText is missing form your theme file
Warning: chat_messageLinkIn is missing form your theme file
Looking for overrides at in/Dark Accent.map
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/TThemes/TThemeConverter/converter.readMapFile(0xc0434de520, 0x12, 0x0)
	C:/Users/user/go/src/github.com/TThemes/TThemeConverter/converter/converter.go:43 +0x34a
github.com/TThemes/TThemeConverter/converter.readOverridesMapFile(0xc0434de500, 0x1a, 0x3)
	C:/Users/user/go/src/github.com/TThemes/TThemeConverter/converter/converter.go:22 +0x239
github.com/TThemes/TThemeConverter/converter.applyConvMap(0xc0420640c0, 0xc0434aa2a0, 0xc0434aa270, 0xc04203bf50, 0x26, 0x26)
	C:/Users/user/go/src/github.com/TThemes/TThemeConverter/converter/converter.go:74 +0x2eb
github.com/TThemes/TThemeConverter/converter.Convert(0xc0420391f0, 0xc042039200, 0xc042038d9c)
	C:/Users/user/go/src/github.com/TThemes/TThemeConverter/converter/converter.go:103 +0x331
main.main()
	C:/Users/user/go/src/github.com/TThemes/TThemeConverter/main.go:20 +0x131
```

**Comment by Slimd0g** [comment]
Don't forget situation, when comment is on separate line.
Example:
```
// Main colors
key1=#000000
key2=#ffffff
```
